### ISSUE TITLE
Hello, Our organization has a requirement to read thru the posts and comments. How can I achieve the reading of the posts and all the comment using this technique

### ISSUE THREAD

**Issue by shyamsuthar** [linkedin-developers/linkedin-api-python-client#15]

**Comment by shimizust** [comment]
Hi @shyamsuthar, is there a specific issue with implementing using the API clients? These are agnostic to specific APIs, but I can try to point you in the right direction.

You probably will need access to the Community Management API product. Then you can take a look at the following API docs for [retrieving posts by organization](https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/posts-api?view=li-lms-2023-03&tabs=http#find-posts-by-authors) and [retrieving comments by post](https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/comments-api?view=li-lms-2023-03&tabs=http).

In the /examples directory of this repo, there is an example for using the API clients to create posts (on behalf of an authenticated member).
