### ISSUE TITLE
Encountered an error while using the sample code: error occurred when calling the 'get()' method.

### ISSUE THREAD

**Issue by dalaba7046** [linkedin-developers/linkedin-api-python-client#22]
The following error occurred when using the sample code to modify it for requesting API with my personal information.
![image](https://user-images.githubusercontent.com/49179942/234240013-a2a5a74d-a01e-492f-a58f-62cb6676a78c.png)
Here is the API URL generated by using the sample code. Could you please confirm whether it is correct? As all LinkedIn API documentation examples do not support the latest version of the API URL, I cannot understand the request rules for Advertising API endpoints.
![image](https://user-images.githubusercontent.com/49179942/234240219-1535e54c-1b64-4892-b73c-d367751cd5bc.png)

**Comment by dalaba7046** [comment]
Of course, here is my code.
from linkedin_api.clients.restli.client import RestliClient

from src.utils import file_utils
import json

args = file_utils.load_api_config('LinkedIn')

MY_ACCESS_TOKEN = args['access_token']
account_id = args['account_id']

restli_client = RestliClient()

response = restli_client.get(
  resource_path="/adAccounts/{id}",
  path_keys={ "id": account_id },
  query_params={ "fields": "id,name" },
  access_token=MY_ACCESS_TOKEN,
  version_string="202303"
)
ad_account = response.entity

And,yes I want to fetch all the active Ad Analytics under a specific ad account. I have applied for Advertising API permissions and obtained a token. However, the status code I obtained through the official example is 500.

**Comment by Mouhamet99** [comment]
I think that the issue is not related to LinkedIn api python client as I tested the 'same code' with my own data and it works fine. The issue may be specific to your environment or code. Have you checked if all the dependencies and configurations are properly installed on your machine? Can you provide more details about the error you are encountering?
I am working on a project that uses FastAPI, and here is the code I am currently using.
```python
@router.get("/{ad_account_id}", summary="Fetch an ad account ")
def get_ad_account(ad_account_id: int ):
    """Fetch an ad account by specifying its id"""
    get_response = restli_client.get(
        resource_path="/adAccounts/{id}",
        path_keys={"id": ad_account_id},
        query_params={"fields": "id,name"},
        access_token=ACCESS_TOKEN,
        version_string="202303"
    )
    return get_response.entity

```

**Comment by dalaba7046** [comment]
Thank you for your help in confirming that the issue is not with the LinkedIn API client. 
Regarding the suggestion of providing more detailed error messages, I would love to do so, 
but the error messages returned by the LinkedIn API after my requests are too rudimentary to provide more information. 
I will conduct further testing to address my issue. 
Once again, thank you for your help.

**Comment by shimizust** [comment]
Thanks @Mouhamet99 for confirming the example works.

@dalaba7046 One thing to try besides writing your own python script/app and to eliminate other issues--try git cloning this repo and following the instructions to run the crud_ad_accounts.py example. With a valid access token set, that should just run through everything, including fetching a specific ad account.
