### ISSUE TITLE
timeIntervals cannot used (RestliClient version 2.0.0)

### ISSUE THREAD

**Issue by Qambitions** [linkedin-developers/linkedin-api-python-client#23]
```python
restli_client = RestliClient() 
ACCESS_TOKEN = 'AQUF2Oxxxx' 
response = restli_client.finder(
    resource_path="/organizationalEntityShareStatistics",
    access_token=ACCESS_TOKEN,
    finder_name="organizationalEntity",
    query_params={
        "organizationalEntity":"urn:li:organization:xxxxxxx",
        "timeIntervals":"timeRange:(start=1681798401000,end=1684390401000),timeGranularityType:DAY"
    },
)

print(response.response.text)
```

I follow the document (https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/organizations/share-statistics?tabs=curl&view=li-lms-2023-05#schema) to put the right "timeIntervals" but its not working and return 

> {"message":"Parameter 'timeIntervals' is invalid","status":400}

could you tell me how to use timeIntervals fields

**Comment by Mouhamet99** [comment]
Hi @Qambitions 

Thank you for reaching out with your question about using the timeIntervals field. I'm happy to assist you. 
In your initial code snippet, the timeIntervals parameter is not formatted correctly. Here's the updated code snippet with the correct syntax:
```py
response = restli_client.finder(
    resource_path="/organizationalEntityShareStatistics",
    access_token=ACCESS_TOKEN,
    finder_name="organizationalEntity",
    query_params={
        "organizationalEntity": "urn:li:organization:xxxxxxx",
        "timeIntervals": {
            "timeGranularityType": "DAY",
            "timeRange": {
                "start": 1681798401000,
                "end": 1684390401000
            }
        }
    }
)
````
In this updated code, the timeIntervals parameter is properly structured with the timeGranularityType and timeRange fields.

Please note that the values for the start and end timestamps should be provided in milliseconds. Make sure to adjust these values according to your specific time range requirements.
If you have any further questions or need additional assistance, please feel free to ask.

**Comment by Qambitions** [comment]
``` python
response = restli_client.finder(
  resource_path="/adAnalyticsV2",
  finder_name="statistics",
  query_params={
      "campaigns":["urn:li:sponsoredCampaign:xxxxx"],
      "timeGranularity":"DAILY",
      "pivots":[
          {"value":"COMPANY"},
          {"value":"CAMPAIGN"}
        ],
      "dateRange": {        
        "start": {
            "year" : "2022",
            "month" : "05",
            "day" : "28",
        }
      } 
  },
  access_token=ACCESS_TOKEN,
)
print(response.response.text)
```

How about the pivots? i tried many ways but its still returning 
>{"message":"Invalid value type for parameter pivots","status":400}

**Comment by Mouhamet99** [comment]
Hi @Qambitions ,

Thank you for your message. 
Unfortunately, I dont have enough authorization to make a request to this endpoint.  
So I noticed that you are using the unversioned API for LinkedIn advertising. It is recommended to use the versioned API for better compatibility and future-proofing your code.

To use the versioned API, you need to make the following changes:

Update the resource path from "/adAnalyticsV2" to "/adAnalytics". This ensures that you are accessing the correct resource path for the versioned API.

Add the **version_string** property and set it to the desired API version you want to use. For example, if you want to use version 2023 of the API, you would set **version_string**="2023".

Here is an example of the updated code:
```py
response = restli_client.finder(
  resource_path="/adAnalytics",
  finder_name="statistics",
  query_params={
     ......
  },
  access_token=ACCESS_TOKEN,
  version_string ="2023",
)
```

**Comment by shimizust** [comment]
Thanks for helping out @Mouhamet99. Just one thing to note, the version_string is of the format "YYYYMMDD", like "20230401".

@Qambitions  I'm not familiar with this API, but it looks like "CAMPAIGN" is not a valid pivot type. See here for the supported pivot values: https://learn.microsoft.com/en-us/linkedin/marketing/integrations/ads-reporting/ads-reporting?view=li-lms-2023-05&tabs=http
