### ISSUE TITLE
Does this only support the xrestli protocol version 2.0.0?

### ISSUE THREAD

**Issue by nbro10** [linkedin-developers/linkedin-api-python-client#30]
The readme states that this library supports xrestli 2.0.0, but does it **also** support version 1.0.0? 

I'm asking this because I remember that there were some features that were not yet available in one protocol or the other. 

I've been reading the code, but I have not yet found the part of the code that would answer this question. Methods doesn't seem to allow you to specify the xrestli protocol version but only the API version.

**Comment by shimizust** [comment]
Yes, this purposefully only supports restli protocol version 2.0.0. Version 1.0.0 has been deprecated for a long time. AFAIK, there is no feature gap between 1.0.0 and 2.0.0 protocol versions.
