### ISSUE TITLE
How would you get the ad accounts by authenticated user?

### ISSUE THREAD

**Issue by nbro10** [linkedin-developers/linkedin-api-python-client#31]
[The documentation](https://learn.microsoft.com/en-us/linkedin/marketing/integrations/ads/account-structure/create-and-manage-account-users?view=li-lms-2023-06&tabs=http#find-ad-accounts-by-authenticated-user) says that we can get the ad accounts by authenticated user by making a GET request to:

> GET https://api.linkedin.com/rest/adAccountUsers?q=authenticatedUser

I was trying to use this library to get this data using something like

```
from linkedin_api.clients.restli.client import RestliClient

restli_client = RestliClient()
access_token = "my-access-token"

response = restli_client.get(
            resource_path="/adAccountUsers",
            access_token=access_token,
            path_keys=None,
            query_params={"q": "authenticatedUser"},
            version_string="202209",
        )
```

But `response.entity` is

```
{'code': 'ILLEGAL_ARGUMENT',
 'message': 'Resource method could not be resolved from request parameters.',
 'status': 400}
```

But, using the same access token, I can call the `/me` endpoint, and get the data I need

```
response = restli_client.get(
            resource_path="/me",
            access_token=access_token,
            path_keys=None,
            version_string="202209")

```

Previously, I was able to make a request to `https://api.linkedin.com/rest/adAccountUsers?q=authenticatedUser` using the same access token without this library, so this may be a bug or a misuse of the library.

**Comment by shimizust** [comment]
@nbro10 The issue is that this is actually a FINDER call (I know, it's not very clear in the docs). Basically any "q=" parameter indicates this is a FINDER request. When you use the client to make a .get() request, instead of .finder(), it will set the "X-Restli-Method" header as "GET" instead of "FINDER", hence the error.

You can try doing something like this:
```
restli_client.finder(
   resource_path="/adAccountUsers",
   access_token=access_token,
   finder_name="authenticatedUser",
   version_string="202209"
)
```

**Comment by shimizust** [comment]
You'll also notice that the response payload looks something like:
```
{
   "elements": [{<AdAccountUser>}, ...]
}
```

Using the `finder` method ensures you get the correct response interface.

**Comment by shimizust** [comment]
@nbro10 Cool, glad that worked for you

There are 14 Rest.li methods that map to GET/POST/PUT/DELETE HTTP methods, so you could make this argument for most of the client methods.

I think there are a few reasons to keep the finder() method:
- The client methods should align with the Rest.li spec
- The request interface indicates that finderName is a required parameter (vs. an optional one if it were just a query param on a get request)
- The response interface for a finder call is a CollectionResponse, which has a particular format (e.g. elements, pagination, metadata fields) vs. a get call which just returns some entity object.

I think updating the documentation to specify the Rest.li method being used would really help in easily translating docs to api client calls vs. just showing the raw HTTP request. Things start to make a lot more sense with that context. (cc @swathivshenoy )
