### ISSUE TITLE
Getting users post content

### ISSUE THREAD

**Issue by Athe-kunal** [linkedin-developers/linkedin-api-python-client#35]
Thank you for the great work here.
I want to get the post content of some of the users that I am interested in. I have their LinkedIn profile URL and their name. First of all, can I do it with the API, and second, how can I change the resource path [here](https://github.com/linkedin-developers/linkedin-api-python-client#base-request-parameters) to get the desired profile posts? Thanks in advance

**Comment by shimizust** [comment]
Hi @Athe-kunal unfortunately I don't know enough about specific API functionality. You can search for /posts or /ugcPosts in the LinkedIn API documentation for API products that might fit your use case (e.g. https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/posts-api?view=li-lms-2023-06&tabs=http#find-posts-by-authors).
