### ISSUE TITLE
Is it possible to make a batch GET request to get all campaigns?

### ISSUE THREAD

**Issue by nbro10** [linkedin-developers/linkedin-api-python-client#36]
We're currently making a request to `adAnalytics` which uses decorations to get the campaign name, if this is passed as a pivot. However, decorations are deprecated since the LinkedIn version `202306`. So I was trying to rewrite our code so that we don't use decorations, but this actually makes our code more complex, because we need to make several more additional requests and handle them. Although the decoration mechanism wasn't very clean, I think it's actually useful and I think it's a pity you're removing it - I think the best option would be to actually keep it and encourage people to not use it, if you really think there's a better option or you think that make additional request is better.

Anyway, I was trying to make a batch GET request to get all campaigns (based also on [the docs](https://learn.microsoft.com/en-us/linkedin/marketing/integrations/ads/account-structure/create-and-manage-campaigns?view=li-lms-2023-06&tabs=http#get-a-campaign)), but I keep getting a 404, so maybe I'm doing something wrong. I was trying to make request like this

```
campaign_ids = [...] 
path_keys = {"account_id": my_account_id}

response = restli_client.batch_get(
            resource_path="/adAccounts/{account_id}/adCampaigns", 
            ids=campaign_ids,
            access_token="my_access_token",
            path_keys=path_keys,
            query_params={"fields": "name"},
            version_string="202209",
        )
```

I tried with both a list of campaign URNs or a list of IDs (extracted from the URNs). I tried without the `query_params`, but I can't get the data and I get 404 or 400 errors. The other problem is that `response.errors` doesn't contain any useful info to debug the issue. Maybe something that can be improved. Maybe it's not a problem with this library but with the API itself which may not return any useful info in the `errors` when they occur

I inspected also the URL, they look like

> https://api.linkedin.com/rest/adAccounts/my_account_id/adCampaigns?ids=List(some_number,another_number,...)&fields=name

Do I need to use the `batch_finder` method instead? According to [the API docs](https://learn.microsoft.com/en-us/linkedin/marketing/integrations/ads/account-structure/create-and-manage-campaigns?view=li-lms-2023-06&tabs=http#search-for-campaigns), we could search for campaigns by IDs: , but I'm not sure what the syntax would be for the ` finder_criteria` in this case

**Comment by shimizust** [comment]
@nbro10 I'm not able to check myself, but this looks correct to me (i'm assuming the duplicate ids parameters is a typo) and a correct use of batch_get.

You might want to check the corresponding Postman collection for adCampaigns (https://www.postman.com/linkedin-developer-apis)?
