### ISSUE TITLE
This library doesn't currently support LinkedIn API versions `>= 202303`

### ISSUE THREAD

**Issue by nbro10** [linkedin-developers/linkedin-api-python-client#39]
I was trying to use the latest LinkedIn API version, which is currently `202306`, but I couldn't because my calls to the `adAnalytics` endpoint are returning 400 responses with errors like this (see also this issue https://github.com/linkedin-developers/linkedin-api-python-client/issues/38 to know more about how I got to know these error details)

```
{'errorDetailType': 'com.linkedin.common.error.BadRequest',
 'errorDetails': {'inputErrors': [{'code': 'PARAM_INVALID',
                                   'description': 'Invalid value for param; '
                                                  'wrong type or other syntax '
                                                  'error',
                                   'input': {'inputPath': {'fieldPath': 'pivots_0'}}},
                                  {'code': 'PARAM_INVALID',
                                   'description': 'Invalid value for param; '
                                                  'wrong type or other syntax '
                                                  'error',
                                   'input': {'inputPath': {'fieldPath': 'pivots_1'}}},
                                  {'code': 'PARAM_INVALID',
                                   'description': 'Invalid value for param; '
                                                  'wrong type or other syntax '
                                                  'error',
                                   'input': {'inputPath': {'fieldPath': 'pivots_2'}}}]},
 'message': 'Multiple errors occurred during param validation. Please see '
            'errorDetails for more information.',
```

According to the [`Recent Marketing API Changes`](https://learn.microsoft.com/en-us/linkedin/marketing/integrations/recent-changes), since version [`202303`](https://learn.microsoft.com/en-us/linkedin/marketing/integrations/recent-changes?view=li-lms-2023-06#march-2023), the way we specify the pivots is different. So, in my case, instead of `pivots=List(COMPANY,ACCOUNT,CAMPAIGN_GROUP)`, which this Python package does, we should do `pivots=List((value:COMPANY),(value:ACCOUNT),(value:CAMPAIGN_GROUP))` (btw, I tried with this new syntax I was able to get the data).

I know that maintaining multiple incompatible API versions is harder, but I think this package should support these different syntaxes, because otherwise this prevents people from choosing which API version to use while using this package, and this can be a big blocker for the adoption of this package, which in my view can be very useful, assuming it abstracts away all these complications

**Comment by shimizust** [comment]
@nbro10 I'm pretty sure this isn't an issue with the client. The JSON representation of the pivots field has changed from:

```
pivots=["COMPANY", "ACCOUNT"]
```
to

```
pivots=[{ "value": "COMPANY", "value": "ACCOUNT"}]
```

Whoever uses the newer version of this API would need to do a code change to meet the new spec.

I do agree that having an abstraction on top of this would be very helpful, but it shouldn't be done within this client library which is agnostic to specific APIs and versions. Ideally there would be perhaps an ad analytics client that utilizes this lower-level Rest.li client. (cc @swathivshenoy )
