### ISSUE TITLE
{'serviceErrorCode': 100, 'message': 'Not enough permissions to access: GET /me', 'status': 403}

### ISSUE THREAD

**Issue by rsforbes** [linkedin-developers/linkedin-api-python-client#49]
I was running the [Simple API Request Example](https://github.com/linkedin-developers/linkedin-api-python-client#simple-api-request-example) in the README.md and receiving the error in the title. 

```
from linkedin_api.clients.restli.client import RestliClient

restli_client = RestliClient()

response = restli_client.get(
  resource_path="/me",
  access_token=<THREE_LEGGED_ACCESS_TOKEN>
)
print(response.entity)
```

I have a three legged access token, but perhaps I'm not understanding "Request access to the Sign In With LinkedIn API product." The only product that appeared available on the Products Page for my app was "Share on LinkedIn" and "OpenID Connect". The others appear to be more indepeth.

I'm thinking I've overlooked something drastically simple and just don't see it?

**Comment by shimizust** [comment]
Hi @rsforbes I am no longer with the team that manages these API products, but I believe OpenID Connect replaced Sign In With LinkedIn, and the APIs are now different.

This example needs to be updated. @swathivshenoy

**Comment by joaomorossini** [comment]
I'm facing the same issue! The official docs apparently contradict each other. There seems to be some sort of incompatibility with the permissions/scopes

**Comment by joaomorossini** [comment]
> Hi @rsforbes I am no longer with the team that manages these API products, but I believe OpenID Connect replaced Sign In With LinkedIn, and the APIs are now different.
> 
> This example needs to be updated. @swathivshenoy 

Hey man, can you please point us to who could help us with this? Any help will be much appreciated.

**Comment by swathivshenoy** [comment]
Hi @rsforbes @joaomorossini 
The previous `Sign-In with LinkedIn` product is now deprecated and replaced with `Sign-In with LinkedIn using OpenID Connect`
The right way to use this is linked [here](https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin-v2?context=linkedin%2Fconsumer%2Fcontext#api-request-to-retreive-member-details)
You will need to request scopes openid, profile and email and then use that token.
 
I will update the ReadMe to update the example.

**Comment by joaomorossini** [comment]
> Hi @rsforbes @joaomorossini The previous `Sign-In with LinkedIn` product is now deprecated and replaced with `Sign-In with LinkedIn using OpenID Connect`. The right way to use this is linked [here](https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin-v2?context=linkedin%2Fconsumer%2Fcontext#api-request-to-retreive-member-details) You will need to request scopes openid, profile and email and then use that token with the endpoint /userinfo instead of me as indicated [here](https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin-v2?context=linkedin%2Fconsumer%2Fcontext#api-request-to-retreive-member-details).
> 
> I will update the ReadMe to update the example.

Thanks a lot, @swathivshenoy . It worked!
