### ISSUE TITLE
Cannot create access token.

### ISSUE THREAD

**Issue by rozeappletree** [linkedin-developers/linkedin-api-python-client#54]
This issue is not related to the Python client but to https://www.linkedin.com/developers/tools/oauth/token-generator.

I am trying to generate a token but when I click on "Request Access Token"

<img width="754" alt="image" src="https://github.com/linkedin-developers/linkedin-api-python-client/assets/45640029/5888ae00-044b-440e-bac5-897b3e254ed0">

I get this window:

<img width="566" alt="image" src="https://github.com/linkedin-developers/linkedin-api-python-client/assets/45640029/36fbc29f-e545-4ad5-8b47-e0a91a4b1f49">

The same app worked for me in 2022.

**Comment by rozeappletree** [comment]
Is this the right place to ask this question

**Comment by shimizust** [comment]
Hi @INF800, thanks for reporting. This isn't the right place for this though. If there is a bug report, you can ask here: https://linkedin.zendesk.com/hc/en-us
